run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - errorlint
  disable-all: true


issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0