// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: proto/shorturl_service/v1/shorturl.proto

package shorturl

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Url struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl    string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl string                 `protobuf:"bytes,3,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *Url) Reset() {
	*x = Url{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{0}
}

func (x *Url) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Url) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *Url) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

func (x *Url) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type GetLongReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Short string `protobuf:"bytes,1,opt,name=short,proto3" json:"short,omitempty"`
}

func (x *GetLongReq) Reset() {
	*x = GetLongReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongReq) ProtoMessage() {}

func (x *GetLongReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongReq.ProtoReflect.Descriptor instead.
func (*GetLongReq) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{1}
}

func (x *GetLongReq) GetShort() string {
	if x != nil {
		return x.Short
	}
	return ""
}

type GetLongRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LongUrl string `protobuf:"bytes,1,opt,name=long_url,json=longUrl,proto3" json:"long_url,omitempty"`
}

func (x *GetLongRes) Reset() {
	*x = GetLongRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetLongRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLongRes) ProtoMessage() {}

func (x *GetLongRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLongRes.ProtoReflect.Descriptor instead.
func (*GetLongRes) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{2}
}

func (x *GetLongRes) GetLongUrl() string {
	if x != nil {
		return x.LongUrl
	}
	return ""
}

type ShortUrlReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *ShortUrlReq) Reset() {
	*x = ShortUrlReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlReq) ProtoMessage() {}

func (x *ShortUrlReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlReq.ProtoReflect.Descriptor instead.
func (*ShortUrlReq) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{3}
}

func (x *ShortUrlReq) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ShortUrlRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ShortUrl string `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *ShortUrlRes) Reset() {
	*x = ShortUrlRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShortUrlRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortUrlRes) ProtoMessage() {}

func (x *ShortUrlRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortUrlRes.ProtoReflect.Descriptor instead.
func (*ShortUrlRes) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{4}
}

func (x *ShortUrlRes) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ShortUrlRes) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ShortUrl string `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
}

func (x *RedirectReq) Reset() {
	*x = RedirectReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectReq) ProtoMessage() {}

func (x *RedirectReq) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectReq.ProtoReflect.Descriptor instead.
func (*RedirectReq) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{5}
}

func (x *RedirectReq) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type RedirectRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
}

func (x *RedirectRes) Reset() {
	*x = RedirectRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RedirectRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectRes) ProtoMessage() {}

func (x *RedirectRes) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shorturl_service_v1_shorturl_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectRes.ProtoReflect.Descriptor instead.
func (*RedirectRes) Descriptor() ([]byte, []int) {
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP(), []int{6}
}

func (x *RedirectRes) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_proto_shorturl_service_v1_shorturl_proto protoreflect.FileDescriptor

var file_proto_shorturl_service_v1_shorturl_proto_rawDesc = []byte{
	0x0a, 0x28, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x15, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76,
	0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x90, 0x01,
	0x0a, 0x03, 0x55, 0x72, 0x6c, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55,
	0x72, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e, 0x61, 0x6c, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x6f, 0x72, 0x69, 0x67, 0x69, 0x6e,
	0x61, 0x6c, 0x55, 0x72, 0x6c, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x22, 0x22, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73,
	0x68, 0x6f, 0x72, 0x74, 0x22, 0x27, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x6e, 0x67, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x22, 0x1f, 0x0a,
	0x0b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x22, 0x3a,
	0x0a, 0x0b, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1b, 0x0a,
	0x09, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x2a, 0x0a, 0x0b, 0x52, 0x65,
	0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x68, 0x6f,
	0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c, 0x22, 0x1f, 0x0a, 0x0b, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x32, 0xd3, 0x02, 0x0a, 0x0a, 0x55, 0x72, 0x6c, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x6c, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e,
	0x67, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x4c, 0x6f, 0x6e,
	0x67, 0x52, 0x65, 0x71, 0x1a, 0x21, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74,
	0x4c, 0x6f, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x22, 0x1b, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x15, 0x12,
	0x13, 0x2f, 0x76, 0x31, 0x2f, 0x6c, 0x6f, 0x6e, 0x67, 0x55, 0x72, 0x6c, 0x2f, 0x7b, 0x73, 0x68,
	0x6f, 0x72, 0x74, 0x7d, 0x12, 0x6a, 0x0a, 0x08, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72, 0x6c,
	0x12, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f, 0x72, 0x74, 0x55, 0x72,
	0x6c, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x68, 0x6f,
	0x72, 0x74, 0x55, 0x72, 0x6c, 0x52, 0x65, 0x73, 0x22, 0x16, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x10,
	0x3a, 0x01, 0x2a, 0x22, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x65, 0x6e,
	0x12, 0x6b, 0x0a, 0x08, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x12, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x52, 0x65, 0x71,
	0x1a, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x64, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x52, 0x65, 0x73, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x12, 0x0f, 0x2f, 0x76,
	0x31, 0x2f, 0x7b, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x5f, 0x75, 0x72, 0x6c, 0x7d, 0x42, 0x45, 0x5a,
	0x43, 0x73, 0x6f, 0x6c, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x31, 0x2f, 0x61, 0x73, 0x73, 0x69, 0x67,
	0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x2d, 0x33, 0x2d, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x2d, 0x75, 0x72,
	0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x68, 0x6f, 0x72, 0x74, 0x75, 0x72, 0x6c,
	0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x73, 0x68, 0x6f, 0x72,
	0x74, 0x75, 0x72, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_shorturl_service_v1_shorturl_proto_rawDescOnce sync.Once
	file_proto_shorturl_service_v1_shorturl_proto_rawDescData = file_proto_shorturl_service_v1_shorturl_proto_rawDesc
)

func file_proto_shorturl_service_v1_shorturl_proto_rawDescGZIP() []byte {
	file_proto_shorturl_service_v1_shorturl_proto_rawDescOnce.Do(func() {
		file_proto_shorturl_service_v1_shorturl_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_shorturl_service_v1_shorturl_proto_rawDescData)
	})
	return file_proto_shorturl_service_v1_shorturl_proto_rawDescData
}

var file_proto_shorturl_service_v1_shorturl_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_shorturl_service_v1_shorturl_proto_goTypes = []any{
	(*Url)(nil),                   // 0: proto.user_service.v1.Url
	(*GetLongReq)(nil),            // 1: proto.user_service.v1.GetLongReq
	(*GetLongRes)(nil),            // 2: proto.user_service.v1.GetLongRes
	(*ShortUrlReq)(nil),           // 3: proto.user_service.v1.ShortUrlReq
	(*ShortUrlRes)(nil),           // 4: proto.user_service.v1.ShortUrlRes
	(*RedirectReq)(nil),           // 5: proto.user_service.v1.RedirectReq
	(*RedirectRes)(nil),           // 6: proto.user_service.v1.RedirectRes
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_shorturl_service_v1_shorturl_proto_depIdxs = []int32{
	7, // 0: proto.user_service.v1.Url.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: proto.user_service.v1.UrlService.GetLong:input_type -> proto.user_service.v1.GetLongReq
	3, // 2: proto.user_service.v1.UrlService.ShortUrl:input_type -> proto.user_service.v1.ShortUrlReq
	5, // 3: proto.user_service.v1.UrlService.Redirect:input_type -> proto.user_service.v1.RedirectReq
	2, // 4: proto.user_service.v1.UrlService.GetLong:output_type -> proto.user_service.v1.GetLongRes
	4, // 5: proto.user_service.v1.UrlService.ShortUrl:output_type -> proto.user_service.v1.ShortUrlRes
	6, // 6: proto.user_service.v1.UrlService.Redirect:output_type -> proto.user_service.v1.RedirectRes
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_shorturl_service_v1_shorturl_proto_init() }
func file_proto_shorturl_service_v1_shorturl_proto_init() {
	if File_proto_shorturl_service_v1_shorturl_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Url); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*GetLongReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GetLongRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ShortUrlReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*ShortUrlRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*RedirectReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_shorturl_service_v1_shorturl_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*RedirectRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_shorturl_service_v1_shorturl_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shorturl_service_v1_shorturl_proto_goTypes,
		DependencyIndexes: file_proto_shorturl_service_v1_shorturl_proto_depIdxs,
		MessageInfos:      file_proto_shorturl_service_v1_shorturl_proto_msgTypes,
	}.Build()
	File_proto_shorturl_service_v1_shorturl_proto = out.File
	file_proto_shorturl_service_v1_shorturl_proto_rawDesc = nil
	file_proto_shorturl_service_v1_shorturl_proto_goTypes = nil
	file_proto_shorturl_service_v1_shorturl_proto_depIdxs = nil
}
