version: "1"
services:
  postgres-db-read:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  postgres-db-write:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5433
    command: -p 5433
  # app:
  #   image: cqrs-main:v1
  #   ports:
  #     - "8080:8080"
  kafka:
    image: apache/kafka:3.8.0
    ports:
      - 9092:9092

  